server:
  port: 8060

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/user/**
        - id: availability-service
          uri: lb://availability-service
          predicates:
            - Path=/availability/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
        - id: medical-service
          uri: lb://medical-service
          predicates:
            - Path=/medical/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/message/**


# Kubernetes deployment profile
---
spring:
  config:
    activate:
      on-profile: prod

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  instance:
    preferIpAddress: true
    hostname: api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-reg:8761/eureka/