server:
  port: 8085
# Local development profile
spring:
  activate:
    on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/mediconnect
    username: luke
    password: abc123
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Kubernetes deployment profile
---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://postgres:5432/mediconnect
    username: luke
    password: abc123
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  instance:
    preferIpAddress: true
    hostname: medical-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-reg:8761/eureka/
