####################################################################################
#################################### Postgres ######################################
####################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-app
data:
  POSTGRES_DB: mediconnect
  POSTGRES_USER: luke
  POSTGRES_PASSWORD: abc123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres-app
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: "postgres-pv-volume"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: mediconnect
          ports:
            - containerPort: 5432
      volumes:
        - name: mediconnect
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
####################################################################################
#################################### pgAdmin #######################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: pgadmin4@pgadmin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30008
---

####################################################################################
#################################### RabbitMQ ######################################
####################################################################################
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq-app
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-app
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
        - name: rabbitmq-app
          image: rabbitmq:3-management
---
####################################################################################
#################################### Zipkin ########################################
####################################################################################
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin-app
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-app
  template:
    metadata:
      labels:
        app: zipkin-app
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
---
####################################################################################
################################ Profile Service ###################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: lukemacca123/mediconnect-profile-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081


---
####################################################################################
############################## Notification Service ################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: lukemacca123/mediconnect-notification-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---

####################################################################################
############################## Availability Service ################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-deployment
  labels:
    app: availability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: availability
  template:
    metadata:
      labels:
        app: availability
    spec:
      containers:
        - name: availability
          image: lukemacca123/mediconnect-availability-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: availability-service
spec:
  selector:
    app: availability
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
####################################################################################
############################## Appointment Service #################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
  labels:
    app: appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: lukemacca123/mediconnect-appointment-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
####################################################################################
################################ Medical Service ###################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-deployment
  labels:
    app: medical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical
  template:
    metadata:
      labels:
        app: medical
    spec:
      containers:
        - name: medical
          image: lukemacca123/mediconnect-medical-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: medical-service
spec:
  selector:
    app: medical
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
####################################################################################
################################# Chat Service #####################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: lukemacca123/mediconnect-chat-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: lukemacca123/mediconnect-config-server:latest
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
---
####################################################################################
################################## API Gateway #####################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lukemacca123/mediconnect-api-gateway:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060
      nodePort: 30007

---
####################################################################################
################################# Eureka Service ###################################
####################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: service-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-reg
  template:
    metadata:
      labels:
        app: service-reg
    spec:
      containers:
        - name: service-reg
          image: lukemacca123/mediconnect-service-reg:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: service-reg
spec:
  type: NodePort
  selector:
    app: service-reg
  ports:
    - port: 8761
      nodePort: 30009

