version: "3"
services:
  profile_service:
    container_name: profile_service
    image: profile_service:latest
    build:
      context: ../server/profile_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  availability_service:
    container_name: availability_service
    image: availability_service:latest
    build:
      context: ../server/availability_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  communication_service:
    container_name: communication_service
    image: communication_service:latest
    build:
      context: ../server/communication_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  booking_service:
    container_name: booking_service
    image: booking_service:latest
    build:
      context: ../server/booking_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  medication_service:
    container_name: medication_service
    image: medication_service:latest
    build:
      context: ../server/medication_service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

  message_service:
    container_name: message_service
    image: message_service:latest
    build:
      context: ../server/message_service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
      
  prescription_service:
    container_name: prescription_service
    image: prescription_service:latest
    build:
      context: ../server/prescription_service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
  