server:
  port: 8060


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
spring:


  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/user/**

        - id: availability-service
          uri: lb://availability-service
          predicates:
            - Path=/availability/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
        - id: medical-service
          uri: lb://medical-service
          predicates:
            - Path=/medical/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/message/**
