spring:
  application:
    name: availability-service
  config:
    import: configserver:http://localhost:8088

---
spring:
  config:
    import: configserver:http://config-server:8088
    activate:
      on-profile: prod