
name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Availability Module
      run: mvn -f Server/availability_service -B package --f pom.xml
    - name: Test
      run: mvn -f Server/availability_service --batch-mode -D maven.test.failure.ignore=true test

    - name: Build Booking Module
      run: mvn -f Server/booking_service -B package --f pom.xml
    - name: Test
      run: mvn -f Server/booking_service --batch-mode -D maven.test.failure.ignore=true test

    - name: Build Communication Module
      run: mvn -f Server/communication_service -B package --f pom.xml
    - name: Test
      run: mvn -f Server/communication_service --batch-mode -D maven.test.failure.ignore=true test

    - name: Build Profile Module
      run: mvn -f Server/profile_service -B package --f pom.xml
    - name: Test
      run: mvn -f Server/profile_service --batch-mode -D maven.test.failure.ignore=true test




