
name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Profile Service
      run: mvn -f server/profile_service -B package --f pom.xml
      
    - name: Test Profile Service
      run: mvn -f server/profile_service --batch-mode -Dmaven.test.failure.ignore=true test
      
    - name: Build Availability Service
      run: mvn -f server/availability_service -B package --f pom.xml
      
    - name: Test Availability Service
      run: mvn -f server/availability_service --batch-mode -Dmaven.test.failure.ignore=true test
    
    - name: Build Booking Service
      run: mvn -f server/booking_service -B package --f pom.xml
      
    - name: Test Booking Service
      run: mvn -f server/booking_service --batch-mode -Dmaven.test.failure.ignore=true test
    
    - name: Build Communication Service
      run: mvn -f server/communication_service -B package --f pom.xml    
      
    - name: Test Communication Service
      run: mvn -f server/communication_service --batch-mode -Dmaven.test.failure.ignore=true test
      
