
name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Profile Service
      run: mvn -f server/profile_service -B package --f pom.xml
      
    - name: Test Profile Service
      run: mvn -f server/profile_service --batch-mode test
      
    - name: Build Availability Service
      run: mvn -f server/booking_service -B package --f pom.xml
      
    - name: Test Availability Service
      run: mvn -f server/availability_service --batch-mode test
    
    - name: Build Booking Service
      run: mvn -f server/booking_service -B package --f pom.xml
      
    - name: Test Booking Service
      run: mvn -f server/booking_service --batch-mode test
    
    - name: Build Communication Service
      run: mvn -f server/communication_service -B package --f pom.xml    
      
    - name: Build Message Service
      run: mvn -f server/message_service -B package --f pom.xml
      
    - name: Test Message Service
      run: mvn -f server/message_service --batch-mode test
      
    - name: Build Prescription Service
      run: mvn -f server/prescription_service -B package --f pom.xml
      
    - name: Test Prescription Service
      run: mvn -f server/prescription_service --batch-mode test
